language: node_js
os:
  - linux
  # - osx
  # - windows
  # TODO: Activate after Windows build is stable.
node_js:
  - node
  - lts/*
  - 12
  - 12.0.0
  - 11
  - 11.0.0
  - 10
  - 10.0.0
  - 9
  - 9.0.0
  - 8
  - 8.3.0
branches:
  except:
    # Packages not used in Linter and / or test code cannot be tested with CI, so exclude branches of update such packages
    - /^renovate\/(?:can-npm-publish|del-cli|git-branch-is|husky|is-git-status-clean|lint-staged|package-version-git-tag|prettier-package-json|sort-package-json)-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
cache: npm
