language: node_js
os:
  - linux
  # - osx
  # - windows
  # TODO: Activate after Windows build is stable.
node_js:
  - node
  - lts/*
  - 12
  - 12.0.0
  - 11
  - 11.0.0
  - 10
  - 10.0.0
  - 8
  - 8.10.0
cache: npm
