environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "12.0.0"
    - nodejs_version: "11"
    - nodejs_version: "11.0.0"
    - nodejs_version: "10"
    - nodejs_version: "10.0.0"
    - nodejs_version: "9"
    - nodejs_version: "9.0.0"
    - nodejs_version: "8"
    - nodejs_version: "8.3.0"

platform:
  - x86
  - x64

init:
  - git config --global core.autocrlf false

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

branches:
  except:
    # Packages not used in Linter and / or test code cannot be tested with CI, so exclude branches of update such packages
    - /^renovate\/(?:can-npm-publish|del-cli|git-branch-is|husky|is-git-status-clean|lint-staged|package-version-git-tag|prettier-package-json|sort-package-json)-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/

cache:
  - node_modules

build: off
