# no PR builds
pr: none

stages:
  - stage: Test

    jobs:
      - template: azure-pipelines-templates/jobs/lint.yml

      - template: azure-pipelines-templates/jobs/unit-test.yml
        parameters:
          name: Linux
          vmImage: ubuntu-latest

      - template: azure-pipelines-templates/jobs/unit-test.yml
        parameters:
          name: Windows
          vmImage: windows-latest
